name: build image

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: the tag used for the release
        required: true

# curl zip
# - start.sh
# - ras-rs
# - ras.service
# - docker-compose.yml (includes built frontend ghcr image)
# - users.yaml
# - Rocket.toml
jobs:
  collect-required-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.9.1
        with:
          workspaces: "ras-rs"
      - name: build ras-rs
        run: cd ras-rs && cargo build -r
      - name: create required-files folder
        run: mkdir required-files
      - name: replace wget placeholder with actual tag
        run: sed -i 's/#TAG#/tag/' setup.sh
      - name: copy all files to release dir
        run: cp start.sh ras-rs/target/release/ras-rs ras.service docker-compose.yml ras-rs/users.yaml ras-rs/Rocket.toml required-files
      - name: compress to tar.gz
        run: tar -czf ./required-files.tar.gz ./required-files
      - name: Create Release
        uses: ncipollo/release-action@main
        with:
          artifactErrorsFailBuild: true
          artifacts: "required-files.tar.gz,setup.sh"
          tag: ${{inputs.tag}}
  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/gold007-dev/ras-frontend
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
